import LegalShell, { H2, P, UL, LI } from '../components/LegalShell'

export default function TermsPage() {
  return (
    <LegalShell title="Terms of Service" lastUpdated="08 April 2026">
      <P>
        These Terms of Service ("Terms") govern your access to and use of HexaLabs Books
        (the "Service"), an online accounting and invoicing platform operated by HexaLabs
        ("we", "us", or "our"). By creating an account or using the Service, you agree to
        be bound by these Terms.
      </P>

      <H2>1. Eligibility</H2>
      <P>
        You must be at least 18 years old and capable of forming a binding contract under
        Indian law to use the Service. By using HexaLabs Books, you represent that you meet
        these requirements and that the information you provide is accurate and complete.
      </P>

      <H2>2. Account Registration</H2>
      <P>
        You are responsible for maintaining the confidentiality of your account credentials
        and for all activities that occur under your account. You agree to notify us
        immediately of any unauthorised use or security breach.
      </P>

      <H2>3. Subscription & Payment</H2>
      <UL>
        <LI>HexaLabs Books offers a free Starter plan and paid Professional and Business plans.</LI>
        <LI>Paid plans are billed monthly via Razorpay. The plan stays active for 30 days from the date of payment.</LI>
        <LI>There is no auto-renewal — you must manually renew before expiry. If a plan expires without renewal, your account is automatically downgraded to the free Starter plan; your data is preserved.</LI>
        <LI>All prices are in Indian Rupees (INR) and inclusive of applicable taxes unless stated otherwise.</LI>
      </UL>

      <H2>4. Acceptable Use</H2>
      <P>You agree NOT to use the Service to:</P>
      <UL>
        <LI>Violate any applicable laws or regulations.</LI>
        <LI>Upload malicious code, viruses, or content that infringes intellectual property rights.</LI>
        <LI>Attempt to access other organisations' data or compromise the Service's security.</LI>
        <LI>Resell, sublicense, or commercially exploit the Service without our written consent.</LI>
        <LI>Use the Service for fraudulent invoicing, money laundering, or any unlawful financial activity.</LI>
      </UL>

      <H2>5. Your Data</H2>
      <P>
        You retain all ownership rights in the data you upload (customers, invoices, bills,
        attachments, etc.). You grant us a limited licence to store, process, and display
        your data solely for the purpose of providing the Service. We will never sell or
        share your data with third parties for marketing.
      </P>
      <P>
        You can export or delete your data at any time from the Settings page. Upon account
        closure, your data is retained for 30 days then permanently deleted from our active
        systems.
      </P>

      <H2>6. GST and Tax Compliance</H2>
      <P>
        While HexaLabs Books helps you generate GST-compliant invoices, we are not your
        accountant or tax advisor. You are solely responsible for:
      </P>
      <UL>
        <LI>The accuracy of GSTIN, PAN, and other tax details you enter.</LI>
        <LI>Correct classification of supplies as inter-state or intra-state.</LI>
        <LI>Filing GST returns and paying taxes due to the government.</LI>
        <LI>Verifying that figures generated by the Service match your books before relying on them.</LI>
      </UL>

      <H2>7. Service Availability</H2>
      <P>
        We strive for high availability but do not guarantee uninterrupted access. The
        Service is provided on an "as is" and "as available" basis. We may perform scheduled
        maintenance with prior notice, and may experience unscheduled downtime due to
        circumstances beyond our control.
      </P>

      <H2>8. Limitation of Liability</H2>
      <P>
        To the maximum extent permitted by law, HexaLabs and its affiliates shall not be
        liable for any indirect, incidental, special, consequential, or punitive damages,
        or any loss of profits or revenues, arising from your use of the Service. Our total
        liability for any claim shall not exceed the amount you paid us in the 12 months
        preceding the claim.
      </P>

      <H2>9. Termination</H2>
      <P>
        You may close your account at any time by contacting support. We may suspend or
        terminate your account if you breach these Terms, fail to pay subscription fees, or
        engage in fraudulent or unlawful activity.
      </P>

      <H2>10. Changes to Terms</H2>
      <P>
        We may update these Terms from time to time. Material changes will be communicated
        via email or an in-app notice. Continued use of the Service after the effective date
        constitutes acceptance of the revised Terms.
      </P>

      <H2>11. Governing Law</H2>
      <P>
        These Terms are governed by the laws of India. Any disputes shall be subject to the
        exclusive jurisdiction of the courts in Bengaluru, Karnataka.
      </P>

      <H2>12. Contact</H2>
      <P>
        For questions about these Terms, contact us at <a href="mailto:support@hexalabs.online" style={{ color:'var(--accent-2)' }}>support@hexalabs.online</a>.
      </P>
    </LegalShell>
  )
}
