import mongoose from 'mongoose'

const InvoiceLineSchema = new mongoose.Schema({
  description: { type: String, required: true },
  qty:         { type: Number, default: 1 },
  rate:        { type: Number, default: 0 },
  hours:       { type: Number, default: 1 },
  tax:         { type: Number, default: 0 }, // GST %
  amount:      { type: Number, default: 0 },
}, { _id: false })

const InvoiceSchema = new mongoose.Schema({
  orgId:         { type: String, required: true, index: true },
  invoiceNumber: { type: String, required: true },
  status:        { type: String, enum: ['Draft', 'Sent', 'Partial', 'Paid', 'Overdue', 'Cancelled'], default: 'Draft' },

  customer: {
    name:    { type: String, default: '' },
    email:   { type: String, default: '' },
    phone:   { type: String, default: '' },
    address: { type: String, default: '' },
    gstin:   { type: String, default: '' },
  },

  issueDate: { type: Date, default: Date.now },
  dueDate:   { type: Date },

  lineItems: { type: [InvoiceLineSchema], default: [] },

  subtotal:   { type: Number, default: 0 },
  taxTotal:   { type: Number, default: 0 },
  cgstTotal:  { type: Number, default: 0 },
  sgstTotal:  { type: Number, default: 0 },
  igstTotal:  { type: Number, default: 0 },
  taxType:    { type: String, enum: ['intra','inter'], default: 'intra' }, // intra = CGST+SGST, inter = IGST
  total:      { type: Number, default: 0 },
  paidAmount: { type: Number, default: 0 },

  currency: { type: String, default: 'INR' },
  notes:    { type: String, default: '' },
  terms:    { type: String, default: '' },

  template:     { type: String, default: 'classic' },
  paymentToken: { type: String, index: true, default: null },

  // Schema-less custom fields (e.g. PO Reference, Project Code, Cost Center)
  customFields: { type: Map, of: String, default: undefined },

  // TDS / TCS (optional)
  tdsRate:    { type: Number, default: 0 },   // %
  tdsAmount:  { type: Number, default: 0 },
  tdsSection: { type: String, default: '' },  // e.g. 194C, 194J

  // GST e-Invoice (filled when IRN is generated by IRP)
  irn:         { type: String, default: '' },
  irnAckNo:    { type: String, default: '' },
  irnAckDate:  { type: Date,   default: null },
  signedQrCode:{ type: String, default: '' },
  ewayBillNo:  { type: String, default: '' },

  // Source links
  estimateId:    { type: mongoose.Schema.Types.ObjectId, ref: 'Estimate', default: null },
  recurringId:   { type: mongoose.Schema.Types.ObjectId, ref: 'RecurringInvoice', default: null },
}, { timestamps: true })

InvoiceSchema.index({ orgId: 1, invoiceNumber: 1 }, { unique: true })
InvoiceSchema.index({ orgId: 1, issueDate: -1 })
InvoiceSchema.index({ orgId: 1, status: 1 })

export default mongoose.models.Invoice || mongoose.model('Invoice', InvoiceSchema)
